### ISSUE TITLE
How do I use it for the full stack apps?

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode-pwa#102]
I used to be able to debug my full stack app via the following configuration.

```json
{
      "type": "pwa",
      "request": "launch",
      "name": "Client / Server",
      "command": "npm run server",
      "url": "http://localhost:8080/build/web/index.html",
},
```

It is not clear whether this is supported and how user is supposed to configure it.

**Comment by connor4312** [comment]
The top-level config is the same shape of the `chrome` debugger, and today you can nest a `program` which hooks up the Node debugger. All of the normal `node` options are supported in the nested object:

```json
{
  "type": "pwa-chrome",
  "request": "launch",
  "name": "Express",
  "url": "http://localhost:3000",
  "server": {
    "program": "bin/www"
  }
}
```

Compared to running a command in the terminal, specifying a program allows gives us a bit more control to ensure things run well across platforms, as well as the ability to support things like [nvm](https://github.com/nvm-sh/nvm) with `runtimeVersion`, so this is generally the preferred way to do things.

But I realize just running a command is often the easiest way to start debugging from scratch 🙂  In the next nightly (8604bef840dc114289ce20caf766222983bd7943) you'll be able to alternatively specify a command to run in the terminal, so your config above would become:

```json
{
  "type": "pwa-chrome",
  "request": "launch",
  "name": "Client / Server",
  "url": "http://localhost:3000",
  "server": {
    "command": "npm run server"
  }
}
```
