### ISSUE TITLE
Impossible to find this extension in the marketplace

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pwa#124]
I searched for every cominaton of node, pwa, debugger and could not find it in the extensions viewlet.
I suggest to add some tags, keywords such that search for pwa finds it somehow.
Though if we plan to ship it as part of vscode in the future I guess this does not really matter. Though still wanted to share.

**Comment by roblourens** [comment]
It's just called "javascript debugger" but even that is hard to search for. I added some keywords, hope that helps.
