### ISSUE TITLE
pwa-chrome: Copy Call Stack not working

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pwa#141]
Issue Type: <b>Bug</b>

Testing microsoft/vscode#85984

Copy Call Stack on a stack element in the Call Stack view does nothing.

Extension version: 2019.12.2403
VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:40:39.806Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.20GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|
</details>

**Comment by connor4312** [comment]
I can actually repro this as well with the existing Node.js adapter. @isidorn it looks like https://github.com/microsoft/vscode/commit/a3830f95de7e4b21aa7f5484c5a1d954f2b17b3f caused an issue with context menu items on debug frames--it looks like when dispatched via the context menu they still receive `(accessor, threadId, context)` rather than `(access, context)`.

**Comment by isidorn** [comment]
Thanks for filling this. This is breakagae and a candidate.
Opened this, will fix it today / tomorrow https://github.com/microsoft/vscode/issues/86596
