### ISSUE TITLE
Log has weird characters

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-pwa#145]
At certain point while inspecting the log when the program was running I got this (I don't know how to reproduce it):

![image](https://user-images.githubusercontent.com/14098140/70099300-4ce42100-15e3-11ea-843e-9bcadc8bcf16.png)

 (It seems like a null character)

**Comment by connor4312** [comment]
I think this is due to the file logger being re-initialized before being closed in some scenarios. Not critical since afaik this doesn't result in a loss of logs, and the pwa-analyzer will just exclude any lines it can't parse into JSON.

**Comment by connor4312** [comment]
Probably fixed in https://github.com/microsoft/vscode-pwa/commit/909d8dced55316c175d7acfc0cc0e6cb39c90d74
