### ISSUE TITLE
Closing a tab gets all Chrome killed

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-pwa#146]
1. Launch the debugger on Chrome
2. Open 3 additional tabs
3. Close the tab that is debugging

Expected:
The other 3 tabs remain open

Actual:
The whole Chrome gets killed

**Comment by connor4312** [comment]
The is currently expected behavior; if we launch Chrome (i.e. it's an instance we 'own') and the user closes the tab we're debugging, we close the browser.

**Comment by digeff** [comment]
Created an user story to track it on the VS Side
