### ISSUE TITLE
pwa-extensionHost: Debug control sometimes disappears

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pwa#148]
Issue Type: <b>Bug</b>

Testing microsoft/vscode#85984

Only seeing this now with extension host debugging:
![image](https://user-images.githubusercontent.com/9205389/70127402-41443900-167b-11ea-8e95-739c24f0ac20.png)

Extension version: 2019.12.3843
VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:29:38.104Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.50GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|
</details>

**Comment by chrmarti** [comment]
Maybe https://github.com/microsoft/vscode/issues/86239.

**Comment by alexandrudima** [comment]
Yes, @isidorn has confirmed it shares the same root cause.

**Comment by isidorn** [comment]
Yes it is the same root cause.
fyi @sbatten and @rebornix
