### ISSUE TITLE
pwa-extensionHost: Multiple extension host nodes after reloading target

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pwa#149]
Issue Type: <b>Bug</b>

Testing microsoft/vscode#85984

Reloading the target appears to leave a node behind:
![image](https://user-images.githubusercontent.com/9205389/70127674-ca5b7000-167b-11ea-89b3-2fe077675920.png)

Extension version: 2019.12.3843
VS Code version: Code - Insiders 1.41.0-insider (43e3581aa635406ada2d8138d7ee242ddabefc1c, 2019-12-04T05:29:38.104Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.50GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|
</details>

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/commit/88e80b9a18b2cc3de0ca3a02977c3e2d4b088a60
