### ISSUE TITLE
Variable scopes are duplicated while doing chrome debugging

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pwa#150]
Testing https://github.com/microsoft/vscode/issues/85984

I was debugging VS Code out of sources using pwa debugger and I see variable scopes are not defined correctly. 

Here are the variables in chrome debugger 

![image](https://user-images.githubusercontent.com/10746682/70138439-95a5e380-1690-11ea-9378-f787aa11ec83.png)

vs pwa debugger

![image](https://user-images.githubusercontent.com/10746682/70138358-6b542600-1690-11ea-98e4-2bbdb4ae8cf6.png)

Breakpoint that was hit is in a function in a class

![image](https://user-images.githubusercontent.com/10746682/70138142-e701a300-168f-11ea-990b-b79b26106b45.png)

**Comment by connor4312** [comment]
Previously PWA used the name, if defined. Now we'll still try to use the name but prefix it if we see a duplicate scope of the same name:

![image](https://user-images.githubusercontent.com/2230985/70189918-723b6280-16a9-11ea-9868-fa498d8b83e2.png)
