### ISSUE TITLE
Browser breakpoints view is shown always

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pwa#152]
Testing https://github.com/microsoft/vscode/issues/85984

Browser breakpoints view is shown always even with initial start experience view:

![image](https://user-images.githubusercontent.com/10746682/70139673-41e8c980-1693-11ea-8b91-7d17acbeb2d7.png)

@isidorn FYI

**Comment by isidorn** [comment]
I already filled this to the PWA extension. So this is a duplicate. However leaving up to @connor4312 to close if he wishes.

**Comment by connor4312** [comment]
Yep, I'll merge with https://github.com/microsoft/vscode-pwa/issues/125, thanks!
