### ISSUE TITLE
PWA fails with an unhelpful message if it's unable to find Chrome

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pwa#153]
Testing https://github.com/microsoft/vscode/issues/85984

Using vscode-smoketest-express or the express demo repo here with following launch.

```json
{
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Express",
            "url": "http://localhost:3000",
            "server": {
                "program": "bin/www"
            }
        }
```

🐛 Unable to launch browser

![image](https://user-images.githubusercontent.com/10746682/70139941-eb2fbf80-1693-11ea-92ad-0578ff4fb351.png)

**Comment by connor4312** [comment]
![image](https://user-images.githubusercontent.com/2230985/70187305-b4ad7100-16a2-11ea-8c3f-d3c308fa2c59.png)
