### ISSUE TITLE
pwa-chrome: Break point is shown inactive

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pwa#154]
Testing https://github.com/microsoft/vscode/issues/85984

- Used Attach to VS Code launch in VS Code OSS with `pwa-chrome`
- Break point was hit but none are shown active

![image](https://user-images.githubusercontent.com/10746682/70140459-018a4b00-1695-11ea-9e1a-17313c9fdc86.png)

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/85148
