### ISSUE TITLE
First CDP message from Node is missing on the logs

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-pwa#23]
The first CDP message from Node doesn't appear on the log because the message is received before setLogConfig(prefix: string, path?: string) is called for the connection, so this._logPath is undefined, and the message is not logged at: async _onMessage(message: string).

This seems to happen because on: async _startSession(socket: net.Socket) { we create the connection const connection = new Connection(new PipeTransport(socket, rawTelemetryReporter), rawTelemetryReporter);
then we declare/await the handler const { targetInfo } = await new Promise<Cdp.Target.TargetCreatedEvent>(f => cdp.Target.on('targetCreated', f));
and after that we call new NodeTarget(this, connection, cdp, targetInfo); which inside has the logic to call setLogConfig

**Comment by connor4312** [comment]
Resolved this in https://github.com/microsoft/vscode-pwa/pull/67
