### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pwa#36]
Keeping a list so we can do it all later

- Ban `var` in source
- Enforce some tslint rules like requiring { } (?)
- 4 space tab width (?)
- Stricter TS rules, like no implicit any
- ~~Set up CI~~
- ~~Component Governance~~
- Enforce single quotes
- Interfaces to start with I (match vscode convention)

**Comment by connor4312** [comment]
Tracking this in #69 and #68
