### ISSUE TITLE
Column breakpoints not implemented

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pwa#40]
- Have this code `x++;   y++; `
- Set a breakpoint after `x`
- The breakpoint moves to `y++`, it should prefer the left breakpoint position.

**Comment by roblourens** [comment]
There is a broken test for this, but actually this is not a big deal now that breakpointLocations exist.

**Comment by connor4312** [comment]
PWA doesn't implement column breakpoints; we should support them as a parity item.
