### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pwa#55]
We need logging similar to what v1/v2 do, for our own debugging and for users who file issues. Including CDP/DAP traffic and useful internal tracing info.

**Comment by connor4312** [comment]
I'll take this next--getting logging going would make debugging in general a lot easier, particular as we go into more intricate work with sourcemaps etc...

**Comment by connor4312** [comment]
Added in https://github.com/microsoft/vscode-pwa/pull/67. I reused the previous "trace" option, but the generated logs are now JSON. I created a tool to view these logs here: https://github.com/microsoft/vscode-pwa-analyzer
