### ISSUE TITLE
Breakpoints in files without a sourcemap don't get hit if executed early

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pwa#79]
https://github.com/microsoft/vscode-pwa/pull/78

**Comment by connor4312** [comment]
Seems to be a thing that happens on all non-sourcemapped scripts. You can try this by setting a breakpoint on a script file containing only `const x = 2 + 2`. About half the time for me, the script will run without hitting the breakpoint.

On sourcemap scripts we have the debugging pause to load maps and then set breakpoint before continuing, but there's no such pause on other scripts. It looks like a simple race condition.

**Comment by roblourens** [comment]
In v1 if your breakpoint is in a .js file, we try to set a breakpoint by url for that filename. This is what I call "optimistic breakpoints" and there is a setting to disable it, as a hack for cases where it causes issues.

If that doesn't work, then in chrome, you can reload the page...

**Comment by roblourens** [comment]
We already already doing this:

> we try to set a breakpoint by url for that filename

I suspect we just would need to wait for the 'configurationDone' event before calling runIfWaitingForDebugger.
