### ISSUE TITLE
Get the extension working without proposed api

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/vscode-pwa#80]
Right now the extension only works on insiders due to the use of `enableProposedApi`. This will need to be resolved before launch.

**Comment by connor4312** [comment]
This is needed to publish to the marketplace, so moving it to dogfood

**Comment by connor4312** [comment]
Rob indicated that we could get this allowlisted to use the proposed API, will look at that tomorrow with him.

**Comment by roblourens** [comment]
I added it to the product.json files. Now we just need to publish with the `--noVerify` flag.
